/*
 * This file is generated by jOOQ.
 */
package com.logankulinski.jooq;


import com.logankulinski.jooq.tables.JhinPicks;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EsportsData extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>esports_data</code>
     */
    public static final EsportsData ESPORTS_DATA = new EsportsData();

    /**
     * The table <code>esports_data.jhin_picks</code>.
     */
    public final JhinPicks JHIN_PICKS = JhinPicks.JHIN_PICKS;

    /**
     * No further instances allowed
     */
    private EsportsData() {
        super("esports_data", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JhinPicks.JHIN_PICKS
        );
    }
}
