/*
 * This file is generated by jOOQ.
 */
package com.logankulinski.jooq;


import com.logankulinski.jooq.tables.JhinPicks;
import com.logankulinski.jooq.tables.records.JhinPicksRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * esports_data.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JhinPicksRecord> KEY_JHIN_PICKS_PRIMARY = Internal.createUniqueKey(JhinPicks.JHIN_PICKS, DSL.name("KEY_jhin_picks_PRIMARY"), new TableField[] { JhinPicks.JHIN_PICKS.GAME_ID }, true);
}
