/*
 * This file is generated by jOOQ.
 */
package com.logankulinski.jooq;


import com.logankulinski.jooq.tables.JhinPicks;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.jhin_picks</code>.
     */
    public static final JhinPicks JHIN_PICKS = JhinPicks.JHIN_PICKS;
}
