/*
 * This file is generated by jOOQ.
 */
package com.logankulinski.jooq;


import com.logankulinski.jooq.tables.EsportsPick;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.esports_pick</code>.
     */
    public static final EsportsPick ESPORTS_PICK = EsportsPick.ESPORTS_PICK;
}
