spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: ${JDBC_DRIVER}
  jooq:
    sql-dialect: ${JOOQ_SQL_DIALECT}
discord:
  channel-id: ${DISCORD_CHANNEL_ID}
  jhin-token: ${DISCORD_JHIN_TOKEN}
  lucian-token: ${DISCORD_LUCIAN_TOKEN}
