/*
 * This file is generated by jOOQ.
 */
package com.logankulinski.jooq.tables.records;


import com.logankulinski.jooq.tables.JhinPicks;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JhinPicksRecord extends UpdatableRecordImpl<JhinPicksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.jhin_picks.game_id</code>.
     */
    public void setGameId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.jhin_picks.game_id</code>.
     */
    public String getGameId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.jhin_picks.message_id</code>.
     */
    public void setMessageId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.jhin_picks.message_id</code>.
     */
    public String getMessageId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.jhin_picks.player</code>.
     */
    public void setPlayer(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.jhin_picks.player</code>.
     */
    public String getPlayer() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.jhin_picks.tournament</code>.
     */
    public void setTournament(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.jhin_picks.tournament</code>.
     */
    public String getTournament() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.jhin_picks.won</code>.
     */
    public void setWon(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.jhin_picks.won</code>.
     */
    public Boolean getWon() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.jhin_picks.timestamp</code>.
     */
    public void setTimestamp(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.jhin_picks.timestamp</code>.
     */
    public OffsetDateTime getTimestamp() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.jhin_picks.vod</code>.
     */
    public void setVod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.jhin_picks.vod</code>.
     */
    public String getVod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.jhin_picks.notified</code>.
     */
    public void setNotified(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.jhin_picks.notified</code>.
     */
    public Boolean getNotified() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JhinPicksRecord
     */
    public JhinPicksRecord() {
        super(JhinPicks.JHIN_PICKS);
    }

    /**
     * Create a detached, initialised JhinPicksRecord
     */
    public JhinPicksRecord(String gameId, String messageId, String player, String tournament, Boolean won, OffsetDateTime timestamp, String vod, Boolean notified) {
        super(JhinPicks.JHIN_PICKS);

        setGameId(gameId);
        setMessageId(messageId);
        setPlayer(player);
        setTournament(tournament);
        setWon(won);
        setTimestamp(timestamp);
        setVod(vod);
        setNotified(notified);
        resetChangedOnNotNull();
    }
}
